// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * blinkdots_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * gif_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1413517010);    // assets/icons8-вай-фай-24 (1).png
LV_IMG_DECLARE(ui_img_873724494);    // assets/icons8-монитор-24.png
LV_IMG_DECLARE(ui_img_915196904);    // assets/icons8-термометр-96.png
LV_IMG_DECLARE(ui_img_1168152027);    // assets/icons8-гигрометр-96.png
LV_IMG_DECLARE(ui_img_622398300);    // assets/icons8-солнце-96.png
LV_IMG_DECLARE(ui_img_46158188);    // assets/icons8-снег-96.png
LV_IMG_DECLARE(ui_img_1177728124);    // assets/icons8-дождь-96.png
LV_IMG_DECLARE(ui_img_1944143706);    // assets/icons8-облака-96.png
LV_IMG_DECLARE(ui_img_1863757787);    // assets/icons8-буря-96.png
LV_IMG_DECLARE(ui_img_1630223647);    // assets/icons8-частичная-облачность-96.png
LV_IMG_DECLARE(ui_img_139835185);    // assets/icons8-мокрый-снег-96.png
LV_IMG_DECLARE(ui_img_moon_png);    // assets/moon.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/fog.png
LV_IMG_DECLARE(ui_img_sound_png);    // assets/sound.png
LV_IMG_DECLARE(ui_img_1230472841);    // assets/icons8-автобус-96.png
LV_IMG_DECLARE(ui_img_835527434);    // assets/icons8-процессор-96.png
LV_IMG_DECLARE(ui_img_1814334269);    // assets/icons8-видеокарта-96.png
LV_IMG_DECLARE(ui_img_2128455418);    // assets/icons8-ssd-96.png
LV_IMG_DECLARE(ui_img_295950423);    // assets/icons8-atmospheric-pressure-96.png
LV_IMG_DECLARE(ui_img_music_png);    // assets/music.png

// FONTS
LV_FONT_DECLARE(ui_font_CooolFont24);
LV_FONT_DECLARE(ui_font_fnt30);
LV_FONT_DECLARE(ui_font_fnt75);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
