// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_main_header = NULL;
lv_obj_t * ui_city = NULL;
lv_obj_t * ui_region = NULL;
lv_obj_t * ui_connections = NULL;
lv_obj_t * ui_loadspin = NULL;
lv_obj_t * ui_wifi_icon = NULL;
lv_obj_t * ui_pc_icon = NULL;
lv_obj_t * ui_temperature = NULL;
lv_obj_t * ui_huminity = NULL;
lv_obj_t * ui_hmbar = NULL;
lv_obj_t * ui_tempbar = NULL;
lv_obj_t * ui_hmlabel = NULL;
lv_obj_t * ui_templabel = NULL;
lv_obj_t * ui_weather_img = NULL;
lv_obj_t * ui_sunny = NULL;
lv_obj_t * ui_snowy = NULL;
lv_obj_t * ui_rainy = NULL;
lv_obj_t * ui_cloudy = NULL;
lv_obj_t * ui_storm = NULL;
lv_obj_t * ui_partly_cloudy = NULL;
lv_obj_t * ui_snow_and_rain = NULL;
lv_obj_t * ui_moon = NULL;
lv_obj_t * ui_fog = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_main_hours = NULL;
lv_obj_t * ui_main_dots = NULL;
lv_obj_t * ui_main_minute = NULL;
lv_obj_t * ui_main_seconds = NULL;
lv_obj_t * ui_other_weather = NULL;
lv_obj_t * ui_other_inf = NULL;
lv_obj_t * ui_date_and_day = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_simb_weather = NULL;
lv_obj_t * ui_gif = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_header = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_main_header);
    lv_obj_set_width(ui_main_header, 240);
    lv_obj_set_height(ui_main_header, 20);
    lv_obj_set_x(ui_main_header, 0);
    lv_obj_set_y(ui_main_header, -110);
    lv_obj_set_align(ui_main_header, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_main_header, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_main_header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_main_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_main_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_city = lv_label_create(ui_main_header);
    lv_obj_set_width(ui_city, 100);
    lv_obj_set_height(ui_city, 20);
    lv_obj_set_x(ui_city, -70);
    lv_obj_set_y(ui_city, -28);
    lv_obj_set_align(ui_city, LV_ALIGN_CENTER);
    lv_label_set_text(ui_city, "Moscow");
    lv_obj_set_style_text_color(ui_city, lv_color_hex(0x00FCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_city, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_city, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_region = lv_label_create(ui_main_header);
    lv_obj_set_width(ui_region, 40);
    lv_obj_set_height(ui_region, 18);
    lv_obj_set_x(ui_region, -18);
    lv_obj_set_y(ui_region, 4);
    lv_obj_set_align(ui_region, LV_ALIGN_CENTER);
    lv_label_set_text(ui_region, "RU");
    lv_obj_set_style_text_color(ui_region, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_region, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_region, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_region, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_region, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_region, lv_color_hex(0x00CFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_region, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connections = lv_obj_create(ui_main_header);
    lv_obj_remove_style_all(ui_connections);
    lv_obj_set_width(ui_connections, 100);
    lv_obj_set_height(ui_connections, 20);
    lv_obj_set_align(ui_connections, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connections, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_connections, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_connections, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loadspin = lv_spinner_create(ui_connections, 1000, 90);
    lv_obj_set_width(ui_loadspin, 20);
    lv_obj_set_height(ui_loadspin, 20);
    lv_obj_set_x(ui_loadspin, 92);
    lv_obj_set_y(ui_loadspin, -80);
    lv_obj_set_align(ui_loadspin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_loadspin, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_loadspin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_loadspin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_loadspin, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_loadspin, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_loadspin, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_loadspin, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_loadspin, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_loadspin, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_wifi_icon = lv_img_create(ui_connections);
    lv_img_set_src(ui_wifi_icon, &ui_img_1413517010);
    lv_obj_set_width(ui_wifi_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi_icon, -13);
    lv_obj_set_y(ui_wifi_icon, -25);
    lv_obj_set_align(ui_wifi_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pc_icon = lv_img_create(ui_connections);
    lv_img_set_src(ui_pc_icon, &ui_img_873724494);
    lv_obj_set_width(ui_pc_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pc_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pc_icon, 20);
    lv_obj_set_y(ui_pc_icon, -21);
    lv_obj_set_align(ui_pc_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pc_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pc_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pc_icon, 200);

    ui_temperature = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_temperature, &ui_img_915196904);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, -98);
    lv_obj_set_y(ui_temperature, 95);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temperature, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_temperature, 90);

    ui_huminity = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_huminity, &ui_img_1168152027);
    lv_obj_set_width(ui_huminity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_huminity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_huminity, -95);
    lv_obj_set_y(ui_huminity, 60);
    lv_obj_set_align(ui_huminity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_huminity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_huminity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_huminity, 90);

    ui_hmbar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_hmbar, 70, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_hmbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_hmbar, 60);
    lv_obj_set_height(ui_hmbar, 15);
    lv_obj_set_x(ui_hmbar, -45);
    lv_obj_set_y(ui_hmbar, 60);
    lv_obj_set_align(ui_hmbar, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_hmbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hmbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hmbar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hmbar, lv_color_hex(0x00FE03), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hmbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_hmbar, lv_color_hex(0xFFC900), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_hmbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_hmbar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_hmbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_tempbar = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_tempbar, -30, 40);
    lv_bar_set_value(ui_tempbar, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_tempbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_tempbar, 60);
    lv_obj_set_height(ui_tempbar, 15);
    lv_obj_set_x(ui_tempbar, -45);
    lv_obj_set_y(ui_tempbar, 95);
    lv_obj_set_align(ui_tempbar, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_tempbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempbar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_tempbar, lv_color_hex(0x0011FE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_tempbar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_tempbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_tempbar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_tempbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_hmlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hmlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hmlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hmlabel, 10);
    lv_obj_set_y(ui_hmlabel, 60);
    lv_obj_set_align(ui_hmlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hmlabel, "100%");
    lv_obj_set_style_text_color(ui_hmlabel, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hmlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hmlabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_templabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_templabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_templabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_templabel, 10);
    lv_obj_set_y(ui_templabel, 95);
    lv_obj_set_align(ui_templabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_templabel, "35°C");
    lv_obj_set_style_text_color(ui_templabel, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_templabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_templabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather_img = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_weather_img);
    lv_obj_set_width(ui_weather_img, 50);
    lv_obj_set_height(ui_weather_img, 50);
    lv_obj_set_x(ui_weather_img, 90);
    lv_obj_set_y(ui_weather_img, -45);
    lv_obj_set_align(ui_weather_img, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather_img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sunny = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_sunny, &ui_img_622398300);
    lv_obj_set_width(ui_sunny, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunny, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sunny, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunny, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunny, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sunny, 150);

    ui_snowy = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_snowy, &ui_img_46158188);
    lv_obj_set_width(ui_snowy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_snowy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_snowy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_snowy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_snowy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_snowy, 150);

    ui_rainy = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_rainy, &ui_img_1177728124);
    lv_obj_set_width(ui_rainy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rainy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rainy, 0);
    lv_obj_set_y(ui_rainy, -4);
    lv_obj_set_align(ui_rainy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rainy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rainy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_rainy, 150);

    ui_cloudy = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_cloudy, &ui_img_1944143706);
    lv_obj_set_width(ui_cloudy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cloudy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cloudy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cloudy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cloudy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_cloudy, 130);

    ui_storm = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_storm, &ui_img_1863757787);
    lv_obj_set_width(ui_storm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_storm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_storm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_storm, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_storm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_storm, 150);

    ui_partly_cloudy = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_partly_cloudy, &ui_img_1630223647);
    lv_obj_set_width(ui_partly_cloudy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_partly_cloudy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_partly_cloudy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_partly_cloudy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_partly_cloudy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_partly_cloudy, 150);

    ui_snow_and_rain = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_snow_and_rain, &ui_img_139835185);
    lv_obj_set_width(ui_snow_and_rain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_snow_and_rain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_snow_and_rain, -2);
    lv_obj_set_y(ui_snow_and_rain, -1);
    lv_obj_set_align(ui_snow_and_rain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_snow_and_rain, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_snow_and_rain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_snow_and_rain, 150);

    ui_moon = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_moon, &ui_img_moon_png);
    lv_obj_set_width(ui_moon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moon, -5);
    lv_obj_set_y(ui_moon, 4);
    lv_obj_set_align(ui_moon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_moon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_moon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_moon, 220);

    ui_fog = lv_img_create(ui_weather_img);
    lv_img_set_src(ui_fog, &ui_img_fog_png);
    lv_obj_set_width(ui_fog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fog, -4);
    lv_obj_set_y(ui_fog, 2);
    lv_obj_set_align(ui_fog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fog, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_fog, 220);

    ui_time = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_time);
    lv_obj_set_width(ui_time, 167);
    lv_obj_set_height(ui_time, 70);
    lv_obj_set_x(ui_time, -35);
    lv_obj_set_y(ui_time, -40);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_time, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_time, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_main_hours = lv_label_create(ui_time);
    lv_obj_set_width(ui_main_hours, 62);
    lv_obj_set_height(ui_main_hours, 62);
    lv_obj_set_x(ui_main_hours, -42);
    lv_obj_set_y(ui_main_hours, 3);
    lv_obj_set_align(ui_main_hours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_hours, "17");
    lv_obj_set_style_text_color(ui_main_hours, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_hours, &ui_font_fnt75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_dots = lv_label_create(ui_time);
    lv_obj_set_width(ui_main_dots, 20);
    lv_obj_set_height(ui_main_dots, 62);
    lv_obj_set_align(ui_main_dots, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_dots, ":");
    lv_obj_set_style_text_color(ui_main_dots, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_dots, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_main_dots, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_dots, &ui_font_fnt75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_minute = lv_label_create(ui_time);
    lv_obj_set_width(ui_main_minute, 62);
    lv_obj_set_height(ui_main_minute, 62);
    lv_obj_set_x(ui_main_minute, 45);
    lv_obj_set_y(ui_main_minute, 4);
    lv_obj_set_align(ui_main_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_minute, "35");
    lv_obj_set_style_text_color(ui_main_minute, lv_color_hex(0x00CFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_minute, &ui_font_fnt75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_seconds = lv_label_create(ui_time);
    lv_obj_set_width(ui_main_seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_main_seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_main_seconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_main_seconds, "38");
    lv_obj_set_style_text_color(ui_main_seconds, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_main_seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_main_seconds, &ui_font_fnt30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_seconds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_seconds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_seconds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_seconds, -5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_other_weather = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_other_weather, 240);
    lv_obj_set_height(ui_other_weather, 32);
    lv_obj_set_x(ui_other_weather, 0);
    lv_obj_set_y(ui_other_weather, -82);
    lv_obj_set_align(ui_other_weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_other_weather, "Feels like 25");
    lv_obj_set_style_text_color(ui_other_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_other_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_other_weather, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_other_weather, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_other_weather, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_other_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_other_weather, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_other_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_other_inf = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_other_inf);
    lv_obj_set_width(ui_other_inf, 240);
    lv_obj_set_height(ui_other_inf, 38);
    lv_obj_set_x(ui_other_inf, 0);
    lv_obj_set_y(ui_other_inf, 15);
    lv_obj_set_align(ui_other_inf, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_other_inf, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_other_inf, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_other_inf, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_date_and_day = lv_obj_create(ui_other_inf);
    lv_obj_remove_style_all(ui_date_and_day);
    lv_obj_set_width(ui_date_and_day, 170);
    lv_obj_set_height(ui_date_and_day, 32);
    lv_obj_set_align(ui_date_and_day, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_date_and_day, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_date_and_day, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_date_and_day, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_date = lv_label_create(ui_date_and_day);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "2/2/2026");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_date_and_day);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "Thur");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0x65BC64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_simb_weather = lv_label_create(ui_other_inf);
    lv_obj_set_width(ui_simb_weather, 65);
    lv_obj_set_height(ui_simb_weather, LV_SIZE_CONTENT);    /// 117
    lv_obj_set_align(ui_simb_weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_simb_weather, "partly cloudy");
    lv_obj_set_style_text_color(ui_simb_weather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_simb_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_simb_weather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_simb_weather, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_simb_weather, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_simb_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_simb_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_simb_weather, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_simb_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_simb_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_simb_weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_simb_weather, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gif = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_gif, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gif, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gif, 80);
    lv_obj_set_y(ui_gif, 80);
    lv_obj_set_align(ui_gif, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gif, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gif, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_main_header = NULL;
    ui_city = NULL;
    ui_region = NULL;
    ui_connections = NULL;
    ui_loadspin = NULL;
    ui_wifi_icon = NULL;
    ui_pc_icon = NULL;
    ui_temperature = NULL;
    ui_huminity = NULL;
    ui_hmbar = NULL;
    ui_tempbar = NULL;
    ui_hmlabel = NULL;
    ui_templabel = NULL;
    ui_weather_img = NULL;
    ui_sunny = NULL;
    ui_snowy = NULL;
    ui_rainy = NULL;
    ui_cloudy = NULL;
    ui_storm = NULL;
    ui_partly_cloudy = NULL;
    ui_snow_and_rain = NULL;
    ui_moon = NULL;
    ui_fog = NULL;
    ui_time = NULL;
    ui_main_hours = NULL;
    ui_main_dots = NULL;
    ui_main_minute = NULL;
    ui_main_seconds = NULL;
    ui_other_weather = NULL;
    ui_other_inf = NULL;
    ui_date_and_day = NULL;
    ui_date = NULL;
    ui_day = NULL;
    ui_simb_weather = NULL;
    ui_gif = NULL;

}
