// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_barometr = NULL;
lv_obj_t * ui_termometr = NULL;
lv_obj_t * ui_hummetter = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_homeprs = NULL;
lv_obj_t * ui_hometemp = NULL;
lv_obj_t * ui_homehum = NULL;
// event funtions

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x0007B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Screen6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Screen6, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 240);
    lv_obj_set_height(ui_Container4, 240);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 105);
    lv_obj_set_height(ui_Container2, 240);
    lv_obj_set_x(ui_Container2, -70);
    lv_obj_set_y(ui_Container2, 0);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_barometr = lv_img_create(ui_Container2);
    lv_img_set_src(ui_barometr, &ui_img_295950423);
    lv_obj_set_width(ui_barometr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_barometr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_barometr, -70);
    lv_obj_set_y(ui_barometr, 73);
    lv_obj_set_align(ui_barometr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barometr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_barometr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_barometr, 200);
    lv_obj_set_style_outline_color(ui_barometr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_barometr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_termometr = lv_img_create(ui_Container2);
    lv_img_set_src(ui_termometr, &ui_img_915196904);
    lv_obj_set_width(ui_termometr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_termometr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_termometr, -73);
    lv_obj_set_y(ui_termometr, -2);
    lv_obj_set_align(ui_termometr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_termometr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_termometr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_termometr, 200);
    lv_obj_set_style_outline_color(ui_termometr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_termometr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hummetter = lv_img_create(ui_Container2);
    lv_img_set_src(ui_hummetter, &ui_img_1168152027);
    lv_obj_set_width(ui_hummetter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hummetter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hummetter, -70);
    lv_obj_set_y(ui_hummetter, -79);
    lv_obj_set_align(ui_hummetter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hummetter, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hummetter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hummetter, 200);
    lv_obj_set_style_outline_color(ui_hummetter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_hummetter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 105);
    lv_obj_set_height(ui_Container3, 240);
    lv_obj_set_x(ui_Container3, 28);
    lv_obj_set_y(ui_Container3, 0);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homeprs = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_homeprs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeprs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_homeprs, 5);
    lv_obj_set_y(ui_homeprs, 83);
    lv_obj_set_align(ui_homeprs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_homeprs, "35");
    lv_obj_set_style_text_font(ui_homeprs, &ui_font_CooolFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hometemp = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_hometemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hometemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hometemp, 25);
    lv_obj_set_y(ui_hometemp, -84);
    lv_obj_set_align(ui_hometemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hometemp, "35");
    lv_obj_set_style_text_font(ui_hometemp, &ui_font_CooolFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homehum = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_homehum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homehum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_homehum, -8);
    lv_obj_set_y(ui_homehum, 40);
    lv_obj_set_align(ui_homehum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_homehum, "35");
    lv_obj_set_style_text_font(ui_homehum, &ui_font_CooolFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Container4 = NULL;
    ui_Container2 = NULL;
    ui_barometr = NULL;
    ui_termometr = NULL;
    ui_hummetter = NULL;
    ui_Container3 = NULL;
    ui_homeprs = NULL;
    ui_hometemp = NULL;
    ui_homehum = NULL;

}
