// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_bus = NULL;
lv_obj_t * ui_header_time = NULL;
lv_obj_t * ui_hours = NULL;
lv_obj_t * ui_dots = NULL;
lv_obj_t * ui_minutes = NULL;
lv_obj_t * ui_bus_list = NULL;
lv_obj_t * ui_bus1 = NULL;
lv_obj_t * ui_bus2 = NULL;
lv_obj_t * ui_bus3 = NULL;
lv_obj_t * ui_bus4 = NULL;
lv_obj_t * ui_bus_times = NULL;
lv_obj_t * ui_bus1_time = NULL;
lv_obj_t * ui_curtime_bus1 = NULL;
lv_obj_t * ui_b1hours1 = NULL;
lv_obj_t * ui_b1dots1 = NULL;
lv_obj_t * ui_b1minutes1 = NULL;
lv_obj_t * ui_b1nexttime1 = NULL;
lv_obj_t * ui_b1hours2 = NULL;
lv_obj_t * ui_b1dots2 = NULL;
lv_obj_t * ui_b1minutes2 = NULL;
lv_obj_t * ui_b1nexttime2 = NULL;
lv_obj_t * ui_b1hours3 = NULL;
lv_obj_t * ui_b1dots3 = NULL;
lv_obj_t * ui_b1minutes3 = NULL;
lv_obj_t * ui_b1nexttime3 = NULL;
lv_obj_t * ui_b1hours4 = NULL;
lv_obj_t * ui_b1dots4 = NULL;
lv_obj_t * ui_b1minutes4 = NULL;
lv_obj_t * ui_bus2_time = NULL;
lv_obj_t * ui_curtime_bus2 = NULL;
lv_obj_t * ui_b2hours1 = NULL;
lv_obj_t * ui_b2dots1 = NULL;
lv_obj_t * ui_b2minutes1 = NULL;
lv_obj_t * ui_b2nexttime1 = NULL;
lv_obj_t * ui_b2hours2 = NULL;
lv_obj_t * ui_b2dots2 = NULL;
lv_obj_t * ui_b2minutes2 = NULL;
lv_obj_t * ui_b2nexttime2 = NULL;
lv_obj_t * ui_b2hours3 = NULL;
lv_obj_t * ui_b2dots3 = NULL;
lv_obj_t * ui_b2minutes3 = NULL;
lv_obj_t * ui_b2nexttime3 = NULL;
lv_obj_t * ui_b2hours4 = NULL;
lv_obj_t * ui_b2dots4 = NULL;
lv_obj_t * ui_b2minutes4 = NULL;
lv_obj_t * ui_bus3_time = NULL;
lv_obj_t * ui_curtime_bus3 = NULL;
lv_obj_t * ui_b3hours1 = NULL;
lv_obj_t * ui_b3dots1 = NULL;
lv_obj_t * ui_b3minutes1 = NULL;
lv_obj_t * ui_b3nexttime1 = NULL;
lv_obj_t * ui_b3hours2 = NULL;
lv_obj_t * ui_b3dots2 = NULL;
lv_obj_t * ui_b3minutes2 = NULL;
lv_obj_t * ui_b3nexttime2 = NULL;
lv_obj_t * ui_b3hours3 = NULL;
lv_obj_t * ui_b3dots3 = NULL;
lv_obj_t * ui_b3minutes3 = NULL;
lv_obj_t * ui_b3nexttime3 = NULL;
lv_obj_t * ui_b3hours4 = NULL;
lv_obj_t * ui_b3dots4 = NULL;
lv_obj_t * ui_b3minutes4 = NULL;
lv_obj_t * ui_bus4_time = NULL;
lv_obj_t * ui_curtime_bus4 = NULL;
lv_obj_t * ui_b4hours1 = NULL;
lv_obj_t * ui_b4dots1 = NULL;
lv_obj_t * ui_b4minutes1 = NULL;
lv_obj_t * ui_b4nexttime1 = NULL;
lv_obj_t * ui_b4hours2 = NULL;
lv_obj_t * ui_b4dots2 = NULL;
lv_obj_t * ui_b4minutes2 = NULL;
lv_obj_t * ui_b4nexttime2 = NULL;
lv_obj_t * ui_b4hours3 = NULL;
lv_obj_t * ui_b4dots3 = NULL;
lv_obj_t * ui_b4minutes3 = NULL;
lv_obj_t * ui_b4nexttime3 = NULL;
lv_obj_t * ui_b4hours4 = NULL;
lv_obj_t * ui_b4dots4 = NULL;
lv_obj_t * ui_b4minutes4 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_header);
    lv_obj_set_width(ui_header, 240);
    lv_obj_set_height(ui_header, 30);
    lv_obj_set_x(ui_header, 0);
    lv_obj_set_y(ui_header, -102);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus = lv_img_create(ui_header);
    lv_img_set_src(ui_bus, &ui_img_1230472841);
    lv_obj_set_width(ui_bus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bus, -27);
    lv_obj_set_y(ui_bus, -2);
    lv_obj_set_align(ui_bus, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_bus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bus, 80);

    ui_header_time = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_header_time);
    lv_obj_set_width(ui_header_time, 60);
    lv_obj_set_height(ui_header_time, 21);
    lv_obj_set_x(ui_header_time, -4);
    lv_obj_set_y(ui_header_time, -4);
    lv_obj_set_align(ui_header_time, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_header_time, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_header_time, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_header_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_time, 23, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header_time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hours = lv_label_create(ui_header_time);
    lv_obj_set_width(ui_hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hours, -39);
    lv_obj_set_y(ui_hours, 1);
    lv_obj_set_align(ui_hours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hours, "12");
    lv_obj_set_style_text_font(ui_hours, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dots = lv_label_create(ui_header_time);
    lv_obj_set_width(ui_dots, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dots, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dots, -20);
    lv_obj_set_y(ui_dots, -1);
    lv_obj_set_align(ui_dots, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dots, ":");
    lv_obj_set_style_text_font(ui_dots, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minutes = lv_label_create(ui_header_time);
    lv_obj_set_width(ui_minutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_minutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minutes, "15");
    lv_obj_set_style_text_font(ui_minutes, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus_list = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_bus_list);
    lv_obj_set_width(ui_bus_list, 50);
    lv_obj_set_height(ui_bus_list, 210);
    lv_obj_set_x(ui_bus_list, 0);
    lv_obj_set_y(ui_bus_list, 16);
    lv_obj_set_align(ui_bus_list, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_bus_list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_bus_list, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bus_list, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_bus_list, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bus_list, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bus_list, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bus_list, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bus_list, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus1 = lv_label_create(ui_bus_list);
    lv_obj_set_width(ui_bus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bus1, 77);
    lv_obj_set_y(ui_bus1, 7);
    lv_obj_set_align(ui_bus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bus1, "BUS1");
    lv_obj_set_style_text_color(ui_bus1, lv_color_hex(0x00B8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_bus1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_bus1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_bus1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus2 = lv_label_create(ui_bus_list);
    lv_obj_set_width(ui_bus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bus2, "BUS2");
    lv_obj_set_style_text_color(ui_bus2, lv_color_hex(0x00B8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bus2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus3 = lv_label_create(ui_bus_list);
    lv_obj_set_width(ui_bus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bus3, "BUS3");
    lv_obj_set_style_text_color(ui_bus3, lv_color_hex(0x00B8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bus3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus4 = lv_label_create(ui_bus_list);
    lv_obj_set_width(ui_bus4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bus4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bus4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bus4, "BUS4");
    lv_obj_set_style_text_color(ui_bus4, lv_color_hex(0x00B8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bus4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus_times = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_bus_times);
    lv_obj_set_width(ui_bus_times, 190);
    lv_obj_set_height(ui_bus_times, 210);
    lv_obj_set_x(ui_bus_times, 26);
    lv_obj_set_y(ui_bus_times, 17);
    lv_obj_set_align(ui_bus_times, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bus_times, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_bus_times, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_bus_times, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bus1_time = lv_obj_create(ui_bus_times);
    lv_obj_remove_style_all(ui_bus1_time);
    lv_obj_set_width(ui_bus1_time, 185);
    lv_obj_set_height(ui_bus1_time, 50);
    lv_obj_set_align(ui_bus1_time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bus1_time, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_bus1_time, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bus1_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_bus1_time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtime_bus1 = lv_obj_create(ui_bus1_time);
    lv_obj_remove_style_all(ui_curtime_bus1);
    lv_obj_set_width(ui_curtime_bus1, 60);
    lv_obj_set_height(ui_curtime_bus1, 21);
    lv_obj_set_x(ui_curtime_bus1, -4);
    lv_obj_set_y(ui_curtime_bus1, -4);
    lv_obj_set_align(ui_curtime_bus1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_curtime_bus1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_curtime_bus1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_curtime_bus1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtime_bus1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtime_bus1, lv_color_hex(0x088B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtime_bus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_curtime_bus1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_curtime_bus1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_curtime_bus1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_curtime_bus1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1hours1 = lv_label_create(ui_curtime_bus1);
    lv_obj_set_width(ui_b1hours1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1hours1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1hours1, -39);
    lv_obj_set_y(ui_b1hours1, 1);
    lv_obj_set_align(ui_b1hours1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1hours1, "12");
    lv_obj_set_style_text_color(ui_b1hours1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1hours1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1hours1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1dots1 = lv_label_create(ui_curtime_bus1);
    lv_obj_set_width(ui_b1dots1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1dots1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1dots1, -20);
    lv_obj_set_y(ui_b1dots1, -1);
    lv_obj_set_align(ui_b1dots1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1dots1, ":");
    lv_obj_set_style_text_color(ui_b1dots1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1dots1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1dots1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1minutes1 = lv_label_create(ui_curtime_bus1);
    lv_obj_set_width(ui_b1minutes1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1minutes1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b1minutes1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1minutes1, "15");
    lv_obj_set_style_text_color(ui_b1minutes1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1minutes1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1minutes1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1nexttime1 = lv_obj_create(ui_bus1_time);
    lv_obj_remove_style_all(ui_b1nexttime1);
    lv_obj_set_width(ui_b1nexttime1, 60);
    lv_obj_set_height(ui_b1nexttime1, 21);
    lv_obj_set_x(ui_b1nexttime1, -4);
    lv_obj_set_y(ui_b1nexttime1, -4);
    lv_obj_set_align(ui_b1nexttime1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b1nexttime1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b1nexttime1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b1nexttime1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b1hours2 = lv_label_create(ui_b1nexttime1);
    lv_obj_set_width(ui_b1hours2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1hours2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1hours2, -39);
    lv_obj_set_y(ui_b1hours2, 1);
    lv_obj_set_align(ui_b1hours2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1hours2, "12");
    lv_obj_set_style_text_color(ui_b1hours2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1hours2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1hours2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1dots2 = lv_label_create(ui_b1nexttime1);
    lv_obj_set_width(ui_b1dots2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1dots2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1dots2, -20);
    lv_obj_set_y(ui_b1dots2, -1);
    lv_obj_set_align(ui_b1dots2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1dots2, ":");
    lv_obj_set_style_text_color(ui_b1dots2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1dots2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1dots2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1minutes2 = lv_label_create(ui_b1nexttime1);
    lv_obj_set_width(ui_b1minutes2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1minutes2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b1minutes2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1minutes2, "15");
    lv_obj_set_style_text_color(ui_b1minutes2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1minutes2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1minutes2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1nexttime2 = lv_obj_create(ui_bus1_time);
    lv_obj_remove_style_all(ui_b1nexttime2);
    lv_obj_set_width(ui_b1nexttime2, 60);
    lv_obj_set_height(ui_b1nexttime2, 21);
    lv_obj_set_x(ui_b1nexttime2, -4);
    lv_obj_set_y(ui_b1nexttime2, -4);
    lv_obj_set_align(ui_b1nexttime2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b1nexttime2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b1nexttime2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b1nexttime2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b1hours3 = lv_label_create(ui_b1nexttime2);
    lv_obj_set_width(ui_b1hours3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1hours3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1hours3, -39);
    lv_obj_set_y(ui_b1hours3, 1);
    lv_obj_set_align(ui_b1hours3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1hours3, "12");
    lv_obj_set_style_text_color(ui_b1hours3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1hours3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1hours3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1dots3 = lv_label_create(ui_b1nexttime2);
    lv_obj_set_width(ui_b1dots3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1dots3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1dots3, -20);
    lv_obj_set_y(ui_b1dots3, -1);
    lv_obj_set_align(ui_b1dots3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1dots3, ":");
    lv_obj_set_style_text_color(ui_b1dots3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1dots3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1dots3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1minutes3 = lv_label_create(ui_b1nexttime2);
    lv_obj_set_width(ui_b1minutes3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1minutes3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b1minutes3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1minutes3, "15");
    lv_obj_set_style_text_color(ui_b1minutes3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1minutes3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1minutes3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1nexttime3 = lv_obj_create(ui_bus1_time);
    lv_obj_remove_style_all(ui_b1nexttime3);
    lv_obj_set_width(ui_b1nexttime3, 60);
    lv_obj_set_height(ui_b1nexttime3, 21);
    lv_obj_set_x(ui_b1nexttime3, -4);
    lv_obj_set_y(ui_b1nexttime3, -4);
    lv_obj_set_align(ui_b1nexttime3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b1nexttime3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b1nexttime3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b1nexttime3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b1hours4 = lv_label_create(ui_b1nexttime3);
    lv_obj_set_width(ui_b1hours4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1hours4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1hours4, -39);
    lv_obj_set_y(ui_b1hours4, 1);
    lv_obj_set_align(ui_b1hours4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1hours4, "12");
    lv_obj_set_style_text_color(ui_b1hours4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1hours4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1hours4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1dots4 = lv_label_create(ui_b1nexttime3);
    lv_obj_set_width(ui_b1dots4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1dots4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b1dots4, -20);
    lv_obj_set_y(ui_b1dots4, -1);
    lv_obj_set_align(ui_b1dots4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1dots4, ":");
    lv_obj_set_style_text_color(ui_b1dots4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1dots4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1dots4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b1minutes4 = lv_label_create(ui_b1nexttime3);
    lv_obj_set_width(ui_b1minutes4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b1minutes4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b1minutes4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b1minutes4, "15");
    lv_obj_set_style_text_color(ui_b1minutes4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b1minutes4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b1minutes4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus2_time = lv_obj_create(ui_bus_times);
    lv_obj_remove_style_all(ui_bus2_time);
    lv_obj_set_width(ui_bus2_time, 185);
    lv_obj_set_height(ui_bus2_time, 50);
    lv_obj_set_align(ui_bus2_time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bus2_time, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_bus2_time, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bus2_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_bus2_time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtime_bus2 = lv_obj_create(ui_bus2_time);
    lv_obj_remove_style_all(ui_curtime_bus2);
    lv_obj_set_width(ui_curtime_bus2, 60);
    lv_obj_set_height(ui_curtime_bus2, 21);
    lv_obj_set_x(ui_curtime_bus2, -4);
    lv_obj_set_y(ui_curtime_bus2, -4);
    lv_obj_set_align(ui_curtime_bus2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_curtime_bus2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_curtime_bus2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_curtime_bus2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtime_bus2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtime_bus2, lv_color_hex(0x088B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtime_bus2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_curtime_bus2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_curtime_bus2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_curtime_bus2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_curtime_bus2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2hours1 = lv_label_create(ui_curtime_bus2);
    lv_obj_set_width(ui_b2hours1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2hours1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2hours1, -39);
    lv_obj_set_y(ui_b2hours1, 1);
    lv_obj_set_align(ui_b2hours1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2hours1, "12");
    lv_obj_set_style_text_color(ui_b2hours1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2hours1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2hours1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2dots1 = lv_label_create(ui_curtime_bus2);
    lv_obj_set_width(ui_b2dots1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2dots1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2dots1, -20);
    lv_obj_set_y(ui_b2dots1, -1);
    lv_obj_set_align(ui_b2dots1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2dots1, ":");
    lv_obj_set_style_text_color(ui_b2dots1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2dots1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2dots1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2minutes1 = lv_label_create(ui_curtime_bus2);
    lv_obj_set_width(ui_b2minutes1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2minutes1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b2minutes1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2minutes1, "15");
    lv_obj_set_style_text_color(ui_b2minutes1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2minutes1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2minutes1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2nexttime1 = lv_obj_create(ui_bus2_time);
    lv_obj_remove_style_all(ui_b2nexttime1);
    lv_obj_set_width(ui_b2nexttime1, 60);
    lv_obj_set_height(ui_b2nexttime1, 21);
    lv_obj_set_x(ui_b2nexttime1, -4);
    lv_obj_set_y(ui_b2nexttime1, -4);
    lv_obj_set_align(ui_b2nexttime1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b2nexttime1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b2nexttime1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b2nexttime1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b2hours2 = lv_label_create(ui_b2nexttime1);
    lv_obj_set_width(ui_b2hours2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2hours2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2hours2, -39);
    lv_obj_set_y(ui_b2hours2, 1);
    lv_obj_set_align(ui_b2hours2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2hours2, "12");
    lv_obj_set_style_text_color(ui_b2hours2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2hours2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2hours2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2dots2 = lv_label_create(ui_b2nexttime1);
    lv_obj_set_width(ui_b2dots2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2dots2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2dots2, -20);
    lv_obj_set_y(ui_b2dots2, -1);
    lv_obj_set_align(ui_b2dots2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2dots2, ":");
    lv_obj_set_style_text_color(ui_b2dots2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2dots2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2dots2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2minutes2 = lv_label_create(ui_b2nexttime1);
    lv_obj_set_width(ui_b2minutes2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2minutes2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b2minutes2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2minutes2, "15");
    lv_obj_set_style_text_color(ui_b2minutes2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2minutes2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2minutes2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2nexttime2 = lv_obj_create(ui_bus2_time);
    lv_obj_remove_style_all(ui_b2nexttime2);
    lv_obj_set_width(ui_b2nexttime2, 60);
    lv_obj_set_height(ui_b2nexttime2, 21);
    lv_obj_set_x(ui_b2nexttime2, -4);
    lv_obj_set_y(ui_b2nexttime2, -4);
    lv_obj_set_align(ui_b2nexttime2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b2nexttime2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b2nexttime2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b2nexttime2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b2hours3 = lv_label_create(ui_b2nexttime2);
    lv_obj_set_width(ui_b2hours3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2hours3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2hours3, -39);
    lv_obj_set_y(ui_b2hours3, 1);
    lv_obj_set_align(ui_b2hours3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2hours3, "12");
    lv_obj_set_style_text_color(ui_b2hours3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2hours3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2hours3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2dots3 = lv_label_create(ui_b2nexttime2);
    lv_obj_set_width(ui_b2dots3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2dots3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2dots3, -20);
    lv_obj_set_y(ui_b2dots3, -1);
    lv_obj_set_align(ui_b2dots3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2dots3, ":");
    lv_obj_set_style_text_color(ui_b2dots3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2dots3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2dots3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2minutes3 = lv_label_create(ui_b2nexttime2);
    lv_obj_set_width(ui_b2minutes3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2minutes3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b2minutes3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2minutes3, "15");
    lv_obj_set_style_text_color(ui_b2minutes3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2minutes3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2minutes3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2nexttime3 = lv_obj_create(ui_bus2_time);
    lv_obj_remove_style_all(ui_b2nexttime3);
    lv_obj_set_width(ui_b2nexttime3, 60);
    lv_obj_set_height(ui_b2nexttime3, 21);
    lv_obj_set_x(ui_b2nexttime3, -4);
    lv_obj_set_y(ui_b2nexttime3, -4);
    lv_obj_set_align(ui_b2nexttime3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b2nexttime3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b2nexttime3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b2nexttime3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b2hours4 = lv_label_create(ui_b2nexttime3);
    lv_obj_set_width(ui_b2hours4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2hours4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2hours4, -39);
    lv_obj_set_y(ui_b2hours4, 1);
    lv_obj_set_align(ui_b2hours4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2hours4, "12");
    lv_obj_set_style_text_color(ui_b2hours4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2hours4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2hours4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2dots4 = lv_label_create(ui_b2nexttime3);
    lv_obj_set_width(ui_b2dots4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2dots4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b2dots4, -20);
    lv_obj_set_y(ui_b2dots4, -1);
    lv_obj_set_align(ui_b2dots4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2dots4, ":");
    lv_obj_set_style_text_color(ui_b2dots4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2dots4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2dots4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b2minutes4 = lv_label_create(ui_b2nexttime3);
    lv_obj_set_width(ui_b2minutes4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b2minutes4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b2minutes4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b2minutes4, "15");
    lv_obj_set_style_text_color(ui_b2minutes4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b2minutes4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b2minutes4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus3_time = lv_obj_create(ui_bus_times);
    lv_obj_remove_style_all(ui_bus3_time);
    lv_obj_set_width(ui_bus3_time, 185);
    lv_obj_set_height(ui_bus3_time, 50);
    lv_obj_set_align(ui_bus3_time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bus3_time, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_bus3_time, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bus3_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_bus3_time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtime_bus3 = lv_obj_create(ui_bus3_time);
    lv_obj_remove_style_all(ui_curtime_bus3);
    lv_obj_set_width(ui_curtime_bus3, 60);
    lv_obj_set_height(ui_curtime_bus3, 21);
    lv_obj_set_x(ui_curtime_bus3, -4);
    lv_obj_set_y(ui_curtime_bus3, -4);
    lv_obj_set_align(ui_curtime_bus3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_curtime_bus3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_curtime_bus3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_curtime_bus3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtime_bus3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtime_bus3, lv_color_hex(0x088B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtime_bus3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_curtime_bus3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_curtime_bus3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_curtime_bus3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_curtime_bus3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3hours1 = lv_label_create(ui_curtime_bus3);
    lv_obj_set_width(ui_b3hours1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3hours1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3hours1, -39);
    lv_obj_set_y(ui_b3hours1, 1);
    lv_obj_set_align(ui_b3hours1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3hours1, "12");
    lv_obj_set_style_text_color(ui_b3hours1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3hours1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3hours1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3dots1 = lv_label_create(ui_curtime_bus3);
    lv_obj_set_width(ui_b3dots1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3dots1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3dots1, -20);
    lv_obj_set_y(ui_b3dots1, -1);
    lv_obj_set_align(ui_b3dots1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3dots1, ":");
    lv_obj_set_style_text_color(ui_b3dots1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3dots1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3dots1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3minutes1 = lv_label_create(ui_curtime_bus3);
    lv_obj_set_width(ui_b3minutes1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3minutes1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b3minutes1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3minutes1, "15");
    lv_obj_set_style_text_color(ui_b3minutes1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3minutes1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3minutes1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3nexttime1 = lv_obj_create(ui_bus3_time);
    lv_obj_remove_style_all(ui_b3nexttime1);
    lv_obj_set_width(ui_b3nexttime1, 60);
    lv_obj_set_height(ui_b3nexttime1, 21);
    lv_obj_set_x(ui_b3nexttime1, -4);
    lv_obj_set_y(ui_b3nexttime1, -4);
    lv_obj_set_align(ui_b3nexttime1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b3nexttime1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b3nexttime1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b3nexttime1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b3hours2 = lv_label_create(ui_b3nexttime1);
    lv_obj_set_width(ui_b3hours2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3hours2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3hours2, -39);
    lv_obj_set_y(ui_b3hours2, 1);
    lv_obj_set_align(ui_b3hours2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3hours2, "12");
    lv_obj_set_style_text_color(ui_b3hours2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3hours2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3hours2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3dots2 = lv_label_create(ui_b3nexttime1);
    lv_obj_set_width(ui_b3dots2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3dots2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3dots2, -20);
    lv_obj_set_y(ui_b3dots2, -1);
    lv_obj_set_align(ui_b3dots2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3dots2, ":");
    lv_obj_set_style_text_color(ui_b3dots2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3dots2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3dots2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3minutes2 = lv_label_create(ui_b3nexttime1);
    lv_obj_set_width(ui_b3minutes2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3minutes2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b3minutes2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3minutes2, "15");
    lv_obj_set_style_text_color(ui_b3minutes2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3minutes2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3minutes2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3nexttime2 = lv_obj_create(ui_bus3_time);
    lv_obj_remove_style_all(ui_b3nexttime2);
    lv_obj_set_width(ui_b3nexttime2, 60);
    lv_obj_set_height(ui_b3nexttime2, 21);
    lv_obj_set_x(ui_b3nexttime2, -4);
    lv_obj_set_y(ui_b3nexttime2, -4);
    lv_obj_set_align(ui_b3nexttime2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b3nexttime2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b3nexttime2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b3nexttime2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b3hours3 = lv_label_create(ui_b3nexttime2);
    lv_obj_set_width(ui_b3hours3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3hours3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3hours3, -39);
    lv_obj_set_y(ui_b3hours3, 1);
    lv_obj_set_align(ui_b3hours3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3hours3, "12");
    lv_obj_set_style_text_color(ui_b3hours3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3hours3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3hours3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3dots3 = lv_label_create(ui_b3nexttime2);
    lv_obj_set_width(ui_b3dots3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3dots3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3dots3, -20);
    lv_obj_set_y(ui_b3dots3, -1);
    lv_obj_set_align(ui_b3dots3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3dots3, ":");
    lv_obj_set_style_text_color(ui_b3dots3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3dots3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3dots3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3minutes3 = lv_label_create(ui_b3nexttime2);
    lv_obj_set_width(ui_b3minutes3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3minutes3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b3minutes3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3minutes3, "15");
    lv_obj_set_style_text_color(ui_b3minutes3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3minutes3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3minutes3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3nexttime3 = lv_obj_create(ui_bus3_time);
    lv_obj_remove_style_all(ui_b3nexttime3);
    lv_obj_set_width(ui_b3nexttime3, 60);
    lv_obj_set_height(ui_b3nexttime3, 21);
    lv_obj_set_x(ui_b3nexttime3, -4);
    lv_obj_set_y(ui_b3nexttime3, -4);
    lv_obj_set_align(ui_b3nexttime3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b3nexttime3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b3nexttime3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b3nexttime3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b3hours4 = lv_label_create(ui_b3nexttime3);
    lv_obj_set_width(ui_b3hours4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3hours4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3hours4, -39);
    lv_obj_set_y(ui_b3hours4, 1);
    lv_obj_set_align(ui_b3hours4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3hours4, "12");
    lv_obj_set_style_text_color(ui_b3hours4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3hours4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3hours4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3dots4 = lv_label_create(ui_b3nexttime3);
    lv_obj_set_width(ui_b3dots4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3dots4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b3dots4, -20);
    lv_obj_set_y(ui_b3dots4, -1);
    lv_obj_set_align(ui_b3dots4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3dots4, ":");
    lv_obj_set_style_text_color(ui_b3dots4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3dots4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3dots4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b3minutes4 = lv_label_create(ui_b3nexttime3);
    lv_obj_set_width(ui_b3minutes4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b3minutes4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b3minutes4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b3minutes4, "15");
    lv_obj_set_style_text_color(ui_b3minutes4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b3minutes4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b3minutes4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bus4_time = lv_obj_create(ui_bus_times);
    lv_obj_remove_style_all(ui_bus4_time);
    lv_obj_set_width(ui_bus4_time, 185);
    lv_obj_set_height(ui_bus4_time, 50);
    lv_obj_set_align(ui_bus4_time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bus4_time, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_bus4_time, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bus4_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_bus4_time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_curtime_bus4 = lv_obj_create(ui_bus4_time);
    lv_obj_remove_style_all(ui_curtime_bus4);
    lv_obj_set_width(ui_curtime_bus4, 60);
    lv_obj_set_height(ui_curtime_bus4, 21);
    lv_obj_set_x(ui_curtime_bus4, -4);
    lv_obj_set_y(ui_curtime_bus4, -4);
    lv_obj_set_align(ui_curtime_bus4, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_curtime_bus4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_curtime_bus4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_curtime_bus4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_curtime_bus4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_curtime_bus4, lv_color_hex(0x088B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_curtime_bus4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_curtime_bus4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_curtime_bus4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_curtime_bus4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_curtime_bus4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4hours1 = lv_label_create(ui_curtime_bus4);
    lv_obj_set_width(ui_b4hours1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4hours1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4hours1, -39);
    lv_obj_set_y(ui_b4hours1, 1);
    lv_obj_set_align(ui_b4hours1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4hours1, "12");
    lv_obj_set_style_text_color(ui_b4hours1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4hours1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4hours1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4dots1 = lv_label_create(ui_curtime_bus4);
    lv_obj_set_width(ui_b4dots1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4dots1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4dots1, -20);
    lv_obj_set_y(ui_b4dots1, -1);
    lv_obj_set_align(ui_b4dots1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4dots1, ":");
    lv_obj_set_style_text_color(ui_b4dots1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4dots1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4dots1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4minutes1 = lv_label_create(ui_curtime_bus4);
    lv_obj_set_width(ui_b4minutes1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4minutes1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b4minutes1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4minutes1, "15");
    lv_obj_set_style_text_color(ui_b4minutes1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4minutes1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4minutes1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4nexttime1 = lv_obj_create(ui_bus4_time);
    lv_obj_remove_style_all(ui_b4nexttime1);
    lv_obj_set_width(ui_b4nexttime1, 60);
    lv_obj_set_height(ui_b4nexttime1, 21);
    lv_obj_set_x(ui_b4nexttime1, -4);
    lv_obj_set_y(ui_b4nexttime1, -4);
    lv_obj_set_align(ui_b4nexttime1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b4nexttime1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b4nexttime1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b4nexttime1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b4hours2 = lv_label_create(ui_b4nexttime1);
    lv_obj_set_width(ui_b4hours2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4hours2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4hours2, -39);
    lv_obj_set_y(ui_b4hours2, 1);
    lv_obj_set_align(ui_b4hours2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4hours2, "12");
    lv_obj_set_style_text_color(ui_b4hours2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4hours2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4hours2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4dots2 = lv_label_create(ui_b4nexttime1);
    lv_obj_set_width(ui_b4dots2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4dots2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4dots2, -20);
    lv_obj_set_y(ui_b4dots2, -1);
    lv_obj_set_align(ui_b4dots2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4dots2, ":");
    lv_obj_set_style_text_color(ui_b4dots2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4dots2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4dots2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4minutes2 = lv_label_create(ui_b4nexttime1);
    lv_obj_set_width(ui_b4minutes2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4minutes2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b4minutes2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4minutes2, "15");
    lv_obj_set_style_text_color(ui_b4minutes2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4minutes2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4minutes2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4nexttime2 = lv_obj_create(ui_bus4_time);
    lv_obj_remove_style_all(ui_b4nexttime2);
    lv_obj_set_width(ui_b4nexttime2, 60);
    lv_obj_set_height(ui_b4nexttime2, 21);
    lv_obj_set_x(ui_b4nexttime2, -4);
    lv_obj_set_y(ui_b4nexttime2, -4);
    lv_obj_set_align(ui_b4nexttime2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b4nexttime2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b4nexttime2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b4nexttime2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b4hours3 = lv_label_create(ui_b4nexttime2);
    lv_obj_set_width(ui_b4hours3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4hours3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4hours3, -39);
    lv_obj_set_y(ui_b4hours3, 1);
    lv_obj_set_align(ui_b4hours3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4hours3, "12");
    lv_obj_set_style_text_color(ui_b4hours3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4hours3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4hours3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4dots3 = lv_label_create(ui_b4nexttime2);
    lv_obj_set_width(ui_b4dots3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4dots3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4dots3, -20);
    lv_obj_set_y(ui_b4dots3, -1);
    lv_obj_set_align(ui_b4dots3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4dots3, ":");
    lv_obj_set_style_text_color(ui_b4dots3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4dots3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4dots3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4minutes3 = lv_label_create(ui_b4nexttime2);
    lv_obj_set_width(ui_b4minutes3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4minutes3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b4minutes3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4minutes3, "15");
    lv_obj_set_style_text_color(ui_b4minutes3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4minutes3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4minutes3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4nexttime3 = lv_obj_create(ui_bus4_time);
    lv_obj_remove_style_all(ui_b4nexttime3);
    lv_obj_set_width(ui_b4nexttime3, 60);
    lv_obj_set_height(ui_b4nexttime3, 21);
    lv_obj_set_x(ui_b4nexttime3, -4);
    lv_obj_set_y(ui_b4nexttime3, -4);
    lv_obj_set_align(ui_b4nexttime3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_b4nexttime3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_b4nexttime3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_b4nexttime3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_b4hours4 = lv_label_create(ui_b4nexttime3);
    lv_obj_set_width(ui_b4hours4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4hours4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4hours4, -39);
    lv_obj_set_y(ui_b4hours4, 1);
    lv_obj_set_align(ui_b4hours4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4hours4, "12");
    lv_obj_set_style_text_color(ui_b4hours4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4hours4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4hours4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4dots4 = lv_label_create(ui_b4nexttime3);
    lv_obj_set_width(ui_b4dots4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4dots4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_b4dots4, -20);
    lv_obj_set_y(ui_b4dots4, -1);
    lv_obj_set_align(ui_b4dots4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4dots4, ":");
    lv_obj_set_style_text_color(ui_b4dots4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4dots4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4dots4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_b4minutes4 = lv_label_create(ui_b4nexttime3);
    lv_obj_set_width(ui_b4minutes4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_b4minutes4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_b4minutes4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_b4minutes4, "15");
    lv_obj_set_style_text_color(ui_b4minutes4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_b4minutes4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_b4minutes4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_header = NULL;
    ui_bus = NULL;
    ui_header_time = NULL;
    ui_hours = NULL;
    ui_dots = NULL;
    ui_minutes = NULL;
    ui_bus_list = NULL;
    ui_bus1 = NULL;
    ui_bus2 = NULL;
    ui_bus3 = NULL;
    ui_bus4 = NULL;
    ui_bus_times = NULL;
    ui_bus1_time = NULL;
    ui_curtime_bus1 = NULL;
    ui_b1hours1 = NULL;
    ui_b1dots1 = NULL;
    ui_b1minutes1 = NULL;
    ui_b1nexttime1 = NULL;
    ui_b1hours2 = NULL;
    ui_b1dots2 = NULL;
    ui_b1minutes2 = NULL;
    ui_b1nexttime2 = NULL;
    ui_b1hours3 = NULL;
    ui_b1dots3 = NULL;
    ui_b1minutes3 = NULL;
    ui_b1nexttime3 = NULL;
    ui_b1hours4 = NULL;
    ui_b1dots4 = NULL;
    ui_b1minutes4 = NULL;
    ui_bus2_time = NULL;
    ui_curtime_bus2 = NULL;
    ui_b2hours1 = NULL;
    ui_b2dots1 = NULL;
    ui_b2minutes1 = NULL;
    ui_b2nexttime1 = NULL;
    ui_b2hours2 = NULL;
    ui_b2dots2 = NULL;
    ui_b2minutes2 = NULL;
    ui_b2nexttime2 = NULL;
    ui_b2hours3 = NULL;
    ui_b2dots3 = NULL;
    ui_b2minutes3 = NULL;
    ui_b2nexttime3 = NULL;
    ui_b2hours4 = NULL;
    ui_b2dots4 = NULL;
    ui_b2minutes4 = NULL;
    ui_bus3_time = NULL;
    ui_curtime_bus3 = NULL;
    ui_b3hours1 = NULL;
    ui_b3dots1 = NULL;
    ui_b3minutes1 = NULL;
    ui_b3nexttime1 = NULL;
    ui_b3hours2 = NULL;
    ui_b3dots2 = NULL;
    ui_b3minutes2 = NULL;
    ui_b3nexttime2 = NULL;
    ui_b3hours3 = NULL;
    ui_b3dots3 = NULL;
    ui_b3minutes3 = NULL;
    ui_b3nexttime3 = NULL;
    ui_b3hours4 = NULL;
    ui_b3dots4 = NULL;
    ui_b3minutes4 = NULL;
    ui_bus4_time = NULL;
    ui_curtime_bus4 = NULL;
    ui_b4hours1 = NULL;
    ui_b4dots1 = NULL;
    ui_b4minutes1 = NULL;
    ui_b4nexttime1 = NULL;
    ui_b4hours2 = NULL;
    ui_b4dots2 = NULL;
    ui_b4minutes2 = NULL;
    ui_b4nexttime2 = NULL;
    ui_b4hours3 = NULL;
    ui_b4dots3 = NULL;
    ui_b4minutes3 = NULL;
    ui_b4nexttime3 = NULL;
    ui_b4hours4 = NULL;
    ui_b4dots4 = NULL;
    ui_b4minutes4 = NULL;

}
