// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_specs = NULL;
lv_obj_t * ui_CPU = NULL;
lv_obj_t * ui_GPU = NULL;
lv_obj_t * ui_RAM = NULL;
lv_obj_t * ui_labels = NULL;
lv_obj_t * ui_cpulabel = NULL;
lv_obj_t * ui_gpulabel = NULL;
lv_obj_t * ui_ramlabel = NULL;
lv_obj_t * ui_bars = NULL;
lv_obj_t * ui_cpu_bar = NULL;
lv_obj_t * ui_gpu_bar = NULL;
lv_obj_t * ui_ram_bar = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 240);
    lv_obj_set_height(ui_Container1, 240);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_specs = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_specs);
    lv_obj_set_width(ui_specs, 50);
    lv_obj_set_height(ui_specs, 240);
    lv_obj_set_x(ui_specs, -92);
    lv_obj_set_y(ui_specs, -1);
    lv_obj_set_align(ui_specs, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_specs, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_specs, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_specs, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CPU = lv_img_create(ui_specs);
    lv_img_set_src(ui_CPU, &ui_img_835527434);
    lv_obj_set_width(ui_CPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CPU, 45);
    lv_obj_set_y(ui_CPU, 31);
    lv_obj_set_align(ui_CPU, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CPU, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CPU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CPU, 150);

    ui_GPU = lv_img_create(ui_specs);
    lv_img_set_src(ui_GPU, &ui_img_1814334269);
    lv_obj_set_width(ui_GPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GPU, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GPU, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GPU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_GPU, 150);

    ui_RAM = lv_img_create(ui_specs);
    lv_img_set_src(ui_RAM, &ui_img_2128455418);
    lv_obj_set_width(ui_RAM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RAM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RAM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RAM, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RAM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_RAM, 150);

    ui_labels = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_labels);
    lv_obj_set_width(ui_labels, 38);
    lv_obj_set_height(ui_labels, 240);
    lv_obj_set_x(ui_labels, -96);
    lv_obj_set_y(ui_labels, 2);
    lv_obj_set_align(ui_labels, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_labels, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_labels, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_labels, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_labels, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpulabel = lv_label_create(ui_labels);
    lv_obj_set_width(ui_cpulabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpulabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cpulabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpulabel, "45%");
    lv_obj_set_style_text_color(ui_cpulabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpulabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cpulabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpulabel = lv_label_create(ui_labels);
    lv_obj_set_width(ui_gpulabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpulabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpulabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpulabel, "45%");
    lv_obj_set_style_text_color(ui_gpulabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpulabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ramlabel = lv_label_create(ui_labels);
    lv_obj_set_width(ui_ramlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ramlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ramlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ramlabel, "100%");
    lv_obj_set_style_text_color(ui_ramlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ramlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bars = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_bars);
    lv_obj_set_width(ui_bars, 150);
    lv_obj_set_height(ui_bars, 240);
    lv_obj_set_x(ui_bars, 0);
    lv_obj_set_y(ui_bars, -40);
    lv_obj_set_align(ui_bars, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bars, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_bars, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_bars, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cpu_bar = lv_bar_create(ui_bars);
    lv_bar_set_value(ui_cpu_bar, 55, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_bar, 150);
    lv_obj_set_height(ui_cpu_bar, 25);
    lv_obj_set_x(ui_cpu_bar, 58);
    lv_obj_set_y(ui_cpu_bar, 44);
    lv_obj_set_align(ui_cpu_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cpu_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cpu_bar, lv_color_hex(0x80CDA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_cpu_bar, lv_color_hex(0xCB7575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_cpu_bar, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cpu_bar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cpu_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cpu_bar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cpu_bar, lv_color_hex(0x00FF1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_cpu_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_cpu_bar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_gpu_bar = lv_bar_create(ui_bars);
    lv_bar_set_value(ui_gpu_bar, 90, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_gpu_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_gpu_bar, 150);
    lv_obj_set_height(ui_gpu_bar, 25);
    lv_obj_set_x(ui_gpu_bar, 108);
    lv_obj_set_y(ui_gpu_bar, 51);
    lv_obj_set_align(ui_gpu_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_gpu_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gpu_bar, lv_color_hex(0x80CDA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_gpu_bar, lv_color_hex(0xCB7575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_gpu_bar, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_gpu_bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_gpu_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_gpu_bar, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gpu_bar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gpu_bar, lv_color_hex(0x00FF1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_gpu_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_gpu_bar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ram_bar = lv_bar_create(ui_bars);
    lv_bar_set_value(ui_ram_bar, 65, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ram_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ram_bar, 150);
    lv_obj_set_height(ui_ram_bar, 25);
    lv_obj_set_x(ui_ram_bar, 139);
    lv_obj_set_y(ui_ram_bar, 50);
    lv_obj_set_align(ui_ram_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ram_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ram_bar, lv_color_hex(0x80CDA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ram_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ram_bar, lv_color_hex(0xCB7575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ram_bar, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ram_bar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ram_bar, lv_color_hex(0x00FF1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ram_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ram_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ram_bar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Container1 = NULL;
    ui_specs = NULL;
    ui_CPU = NULL;
    ui_GPU = NULL;
    ui_RAM = NULL;
    ui_labels = NULL;
    ui_cpulabel = NULL;
    ui_gpulabel = NULL;
    ui_ramlabel = NULL;
    ui_bars = NULL;
    ui_cpu_bar = NULL;
    ui_gpu_bar = NULL;
    ui_ram_bar = NULL;

}
