// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_barometr;
extern lv_obj_t * ui_termometr;
extern lv_obj_t * ui_hummetter;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_homeprs;
extern lv_obj_t * ui_hometemp;
extern lv_obj_t * ui_homehum;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

