// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_specs;
extern lv_obj_t * ui_CPU;
extern lv_obj_t * ui_GPU;
extern lv_obj_t * ui_RAM;
extern lv_obj_t * ui_labels;
extern lv_obj_t * ui_cpulabel;
extern lv_obj_t * ui_gpulabel;
extern lv_obj_t * ui_ramlabel;
extern lv_obj_t * ui_bars;
extern lv_obj_t * ui_cpu_bar;
extern lv_obj_t * ui_gpu_bar;
extern lv_obj_t * ui_ram_bar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

