// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_songauthor = NULL;
lv_obj_t * ui_songname = NULL;
// event funtions

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x00608D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen7, lv_color_hex(0x800000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen7, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image1, &ui_img_music_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -40);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_songauthor = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_songauthor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_songauthor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_songauthor, 0);
    lv_obj_set_y(ui_songauthor, 45);
    lv_obj_set_align(ui_songauthor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_songauthor, "Русский размер");
    lv_obj_set_style_text_color(ui_songauthor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_songauthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_songauthor, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_songauthor, &ui_font_CooolFont24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_songauthor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_songauthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_songauthor, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_songauthor, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songname = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_songname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_songname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_songname, 0);
    lv_obj_set_y(ui_songname, 80);
    lv_obj_set_align(ui_songname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_songname, "-Новая Весна-");
    lv_obj_set_style_text_color(ui_songname, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_songname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_songname, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_songname, &ui_font_CooolFont24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_songname, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_songname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Image1 = NULL;
    ui_songauthor = NULL;
    ui_songname = NULL;

}
