// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_main_header;
extern lv_obj_t * ui_city;
extern lv_obj_t * ui_region;
extern lv_obj_t * ui_connections;
extern lv_obj_t * ui_loadspin;
extern lv_obj_t * ui_wifi_icon;
extern lv_obj_t * ui_pc_icon;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_huminity;
extern lv_obj_t * ui_hmbar;
extern lv_obj_t * ui_tempbar;
extern lv_obj_t * ui_hmlabel;
extern lv_obj_t * ui_templabel;
extern lv_obj_t * ui_weather_img;
extern lv_obj_t * ui_sunny;
extern lv_obj_t * ui_snowy;
extern lv_obj_t * ui_rainy;
extern lv_obj_t * ui_cloudy;
extern lv_obj_t * ui_storm;
extern lv_obj_t * ui_partly_cloudy;
extern lv_obj_t * ui_snow_and_rain;
extern lv_obj_t * ui_moon;
extern lv_obj_t * ui_fog;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_main_hours;
extern lv_obj_t * ui_main_dots;
extern lv_obj_t * ui_main_minute;
extern lv_obj_t * ui_main_seconds;
extern lv_obj_t * ui_other_weather;
extern lv_obj_t * ui_other_inf;
extern lv_obj_t * ui_date_and_day;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_simb_weather;
extern lv_obj_t * ui_gif;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

