// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_soundimg = NULL;
lv_obj_t * ui_soundbar = NULL;
lv_obj_t * ui_volume_container = NULL;
lv_obj_t * ui_volume = NULL;
lv_obj_t * ui_volume_value = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundimg = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_soundimg, &ui_img_sound_png);
    lv_obj_set_width(ui_soundimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundimg, 0);
    lv_obj_set_y(ui_soundimg, -20);
    lv_obj_set_align(ui_soundimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_soundimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_soundimg, 500);

    ui_soundbar = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_soundbar, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_soundbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_soundbar, 200);
    lv_obj_set_height(ui_soundbar, 20);
    lv_obj_set_x(ui_soundbar, 0);
    lv_obj_set_y(ui_soundbar, 105);
    lv_obj_set_align(ui_soundbar, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_soundbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_soundbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_soundbar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_soundbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_soundbar, lv_color_hex(0x2BFA00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_soundbar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_soundbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_soundbar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_volume_container = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_volume_container);
    lv_obj_set_width(ui_volume_container, 140);
    lv_obj_set_height(ui_volume_container, 29);
    lv_obj_set_x(ui_volume_container, 0);
    lv_obj_set_y(ui_volume_container, 80);
    lv_obj_set_align(ui_volume_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_volume_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_volume_container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_volume_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volume = lv_label_create(ui_volume_container);
    lv_obj_set_width(ui_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volume, -32);
    lv_obj_set_y(ui_volume, 62);
    lv_obj_set_align(ui_volume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volume, "Volume:");
    lv_obj_set_style_text_color(ui_volume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_volume, &ui_font_fnt30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volume_value = lv_label_create(ui_volume_container);
    lv_obj_set_width(ui_volume_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volume_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volume_value, 10);
    lv_obj_set_y(ui_volume_value, 6);
    lv_obj_set_align(ui_volume_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volume_value, "56");
    lv_obj_set_style_text_color(ui_volume_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_volume_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_volume_value, &ui_font_fnt30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_soundimg = NULL;
    ui_soundbar = NULL;
    ui_volume_container = NULL;
    ui_volume = NULL;
    ui_volume_value = NULL;

}
