// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_bus;
extern lv_obj_t * ui_header_time;
extern lv_obj_t * ui_hours;
extern lv_obj_t * ui_dots;
extern lv_obj_t * ui_minutes;
extern lv_obj_t * ui_bus_list;
extern lv_obj_t * ui_bus1;
extern lv_obj_t * ui_bus2;
extern lv_obj_t * ui_bus3;
extern lv_obj_t * ui_bus4;
extern lv_obj_t * ui_bus_times;
extern lv_obj_t * ui_bus1_time;
extern lv_obj_t * ui_curtime_bus1;
extern lv_obj_t * ui_b1hours1;
extern lv_obj_t * ui_b1dots1;
extern lv_obj_t * ui_b1minutes1;
extern lv_obj_t * ui_b1nexttime1;
extern lv_obj_t * ui_b1hours2;
extern lv_obj_t * ui_b1dots2;
extern lv_obj_t * ui_b1minutes2;
extern lv_obj_t * ui_b1nexttime2;
extern lv_obj_t * ui_b1hours3;
extern lv_obj_t * ui_b1dots3;
extern lv_obj_t * ui_b1minutes3;
extern lv_obj_t * ui_b1nexttime3;
extern lv_obj_t * ui_b1hours4;
extern lv_obj_t * ui_b1dots4;
extern lv_obj_t * ui_b1minutes4;
extern lv_obj_t * ui_bus2_time;
extern lv_obj_t * ui_curtime_bus2;
extern lv_obj_t * ui_b2hours1;
extern lv_obj_t * ui_b2dots1;
extern lv_obj_t * ui_b2minutes1;
extern lv_obj_t * ui_b2nexttime1;
extern lv_obj_t * ui_b2hours2;
extern lv_obj_t * ui_b2dots2;
extern lv_obj_t * ui_b2minutes2;
extern lv_obj_t * ui_b2nexttime2;
extern lv_obj_t * ui_b2hours3;
extern lv_obj_t * ui_b2dots3;
extern lv_obj_t * ui_b2minutes3;
extern lv_obj_t * ui_b2nexttime3;
extern lv_obj_t * ui_b2hours4;
extern lv_obj_t * ui_b2dots4;
extern lv_obj_t * ui_b2minutes4;
extern lv_obj_t * ui_bus3_time;
extern lv_obj_t * ui_curtime_bus3;
extern lv_obj_t * ui_b3hours1;
extern lv_obj_t * ui_b3dots1;
extern lv_obj_t * ui_b3minutes1;
extern lv_obj_t * ui_b3nexttime1;
extern lv_obj_t * ui_b3hours2;
extern lv_obj_t * ui_b3dots2;
extern lv_obj_t * ui_b3minutes2;
extern lv_obj_t * ui_b3nexttime2;
extern lv_obj_t * ui_b3hours3;
extern lv_obj_t * ui_b3dots3;
extern lv_obj_t * ui_b3minutes3;
extern lv_obj_t * ui_b3nexttime3;
extern lv_obj_t * ui_b3hours4;
extern lv_obj_t * ui_b3dots4;
extern lv_obj_t * ui_b3minutes4;
extern lv_obj_t * ui_bus4_time;
extern lv_obj_t * ui_curtime_bus4;
extern lv_obj_t * ui_b4hours1;
extern lv_obj_t * ui_b4dots1;
extern lv_obj_t * ui_b4minutes1;
extern lv_obj_t * ui_b4nexttime1;
extern lv_obj_t * ui_b4hours2;
extern lv_obj_t * ui_b4dots2;
extern lv_obj_t * ui_b4minutes2;
extern lv_obj_t * ui_b4nexttime2;
extern lv_obj_t * ui_b4hours3;
extern lv_obj_t * ui_b4dots3;
extern lv_obj_t * ui_b4minutes3;
extern lv_obj_t * ui_b4nexttime3;
extern lv_obj_t * ui_b4hours4;
extern lv_obj_t * ui_b4dots4;
extern lv_obj_t * ui_b4minutes4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

